// <auto-generated />
namespace POS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Company_User_UserRole2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Company_User_UserRole2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801031529062_Company_User_UserRole2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
